### ISSUE TITLE
TeamCity reports less tests than there actually are with multiple 'describe' levels

### ISSUE THREAD

**Issue by miroslawmajka** [travisjeffery/mocha-teamcity-reporter#26]
We've come across an issue with TeamCity only reporting a limited number of Mocha tests when several 'describe' levels are present. We use this in conjunction with mocha-each:

const withThese = require('mocha-each');

```
describe('@tag1 @tag2 When I do A', function() {
    describe('@tag3 with params B', function() {
        describe('@tag4 and expect C', function() {
            let correctParameters = [
                [1],
                [2],
                [3]
            ];
            withThese(correctParameters )
                .it('does D with %s', (param1) => {
        });
    });
});
```

When this is run locally using the spec reported the amount of tests is correct but within TeamCity the summary is wrong. The log lists all the tests but the ultimate result of the test run is incomplete.

**Comment by racerbajs** [comment]
I have seen the same issue as well.

**Comment by elad-nach** [comment]
I encountered this also - I can point out that this also happens when dynamically generating tests as described [here](https://mochajs.org/#dynamically-generating-tests)

**Comment by miroslawmajka** [comment]
Closing as no response for a while and we are moving on to Cucumber having refactored Mocha to one-level-describe structure.

**Comment by dpaquette** [comment]
I am also encountering this issue. Any chance this issue can be re-opened and hopefully fixed?

**Comment by jamie-sherriff** [comment]
@dpaquette i was not aware this was an issue and i have nested dynamic test suites all the time, are you using mocha-each as well?

**Comment by dpaquette** [comment]
No, we are not using mocha-each. Looking at this a little closer and some of our nested tests are being reported but others are not. I haven't been able to identify what the difference is. If I find anything more I will report here.
