### ISSUE TITLE
Failed tests logged to stderr?

### ISSUE THREAD

**Issue by ebdrup** [travisjeffery/mocha-teamcity-reporter#30]
We use this module a lot. Thanks for making it!
Would it be possible to log failed tests to stderr? If yes, then I will happily make a pull request, otherwise I'll do our own fork. But I would rather do it here.

**Comment by jamie-sherriff** [comment]
@ebdrup Do you still need this? i feel like a change like this would need to be option controlled (off by default), since people probably expect errors to be printed on stdout

**Comment by ebdrup** [comment]
Yep still need it 😀

**Comment by jamie-sherriff** [comment]
Merged into 2.3.0 release by #42
