### ISSUE TITLE
We would like to take over maintenance if you want?

### ISSUE THREAD

**Issue by ebdrup** [travisjeffery/mocha-teamcity-reporter#32]
If you would like us to, we at debitoor would like to take over maintenance of this module.
We are quite a few people at debitoor, and we have changing employees. So my suggestion would be that you transfer the repo to our GitHub org `debitoor` and add me on `npm` my npm name is `ebdrup`. Then I can add the other team members on `npm`.

**Comment by jamie-sherriff** [comment]
I also would like to make some changes, has there been any movement on deciding where the future maintenance is going? @ebdrup @travisjeffery

**Comment by fatso83** [comment]
Try pinging him on Twitter or his email. Both in the profile. People often turn off notifications on repos they no longer have any interest in.

**Comment by jamie-sherriff** [comment]
Ah thanks, assumed he was a busy man and didn't want to interrupt him. Anyways i forked the project and republished it as mocha-teamcity-reporter-v2 if anyone else sees this and would like to make changes.

**Comment by fatso83** [comment]
@jamie-sherriff Yeah, I saw that :+1:  A sidenote is that I think it makes more sense to publish forked versions as "<username>/<package>" now that NPM has supported scopes for a while. "Use jamie's NPM fork is less prone to miscommunication than "use version two of the first version of the package, not the first version of the second version of the package". My two cents :-)

**Comment by travisjeffery** [comment]
Sorry, just seeing these now. Yeah GitHub notifications are a mess for me. Thanks to https://twitter.com/kopseng/status/937599914963537920 for shooting me a tweet. I've added both @ebdrup  and @jamie-sherriff as collaborators.

**Comment by jamie-sherriff** [comment]
@travisjeffery  Thanks a lot! and sorry for the delay. Do you still have time to publish new updates to npm or can you add someone else as a collaborator?

@fatso83  yea good idea! one of those in hindsight things :)

**Comment by travisjeffery** [comment]
@jamie-sherriff added you to the pkg on npm.

**Comment by travisjeffery** [comment]
If there are others who want to help let me know.

**Comment by jamie-sherriff** [comment]
Thanks @travisjeffery
