### ISSUE TITLE
Tag 3.0.0 release

### ISSUE THREAD

**Issue by DamienCassou** [travisjeffery/mocha-teamcity-reporter#52]
Apparently, 3.x is released but it doesn't appear in https://github.com/travisjeffery/mocha-teamcity-reporter/releases.

**Comment by jamie-sherriff** [comment]
@DamienCassou Thanks, 

Had missed a few tags so they are pushed up now. I have only updated the tag for release on the latest version on github otherwise please refer to the CHANGELOG.md file in the repo for previous versions

**Comment by DamienCassou** [comment]
Thank you.
