### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by marius-hi** [travisjeffery/mocha-teamcity-reporter#53]
Trying to use this reporter with Cypress and parallelization mode : https://docs.cypress.io/guides/guides/parallelization.html#Overview
This means that my tests are distributed on a multiple number of machines which run tests in parallel.

Everything works fine with the exception that a failing test is wrongly displayed under another describe.

Example:
describe('Describe A', () => {
    it('should test 1', () => { });
    it('should test 2', () => { });
});
describe('Describe B', () => {
  it('should test 3', () => { });
  it('should test 4', () => { });
});

On Teamcity I may get reported that the failing test 'should test 3' or 'should test 4' belongs to 'Describe A' and 'should test 1' or 'should test 2' belong to 'Describe B'.

Is there any way to use this reporter and run the tests in parallel?

**Comment by jamie-sherriff** [comment]
Hey @marius-hi 
Sorry for the delay in getting to this.

Any idea what version of mocha is being used in cypress?

Are you using different flowIds for each machine in parallel?

Any chance you have a minimum working example you could post? If not do you have the teamcity stdout messages
e.g
##teamcity[testStarted name='MyTest.test1']
##teamcity[testFailed name='MyTest.test1' message='failure message' details='message and stack trace']
##teamcity[testFinished name='MyTest.test1']

**Comment by marius-acslworld** [comment]
Hey @jamie-sherriff,

I didn't specify the flowId parameter and this was the reason why the tests were grouped in a wrong suite. 
When one of the machines emitted suite start message, the other machine was emitting test failed message.

Thanks for your support

**Comment by marius-hi** [comment]
Hey @jamie-sherriff ,

I didn't specify the flowId parameter and this was the reason why the tests were grouped in a wrong suite. 
When one of the machines emitted suite start message, the other machine was emitting test failed message.

Thanks for your support
