### ISSUE TITLE
Implement 'hook end' event

### ISSUE THREAD

**Issue by cspotcode** [travisjeffery/mocha-teamcity-reporter#54]
## The problem

Does not emit `testFinished` message when a hook ends. (`before`, `beforeEach`, etc)
This means the grouping in TC's log is broken, because peers of the hook are erroneously shown as children of the hook.

## Environment

* What mocha-teamcity-reporter version are you using: 3.0.0
* Version of NPM/yarn etc and Node.js: npm 6.13.4, node 14.0.0
* Version of teamcity (If Applicable) 2019.2.1
* Using mocha 7.1.1

## Details

A "Test start" message is emitted when a hook is run, but no corresponding "Test finished"
https://github.com/travisjeffery/mocha-teamcity-reporter/blob/master/lib/teamcity.js#L131-L135

**Comment by jamie-sherriff** [comment]
Hey @cspotcode  Sorry i have been busy lately, can see how this is an issue and i would certainly welcome a PR if you have time, otherwise i can try take a look when i get a chance.

**Comment by cspotcode** [comment]
Unfortunately I don't have time.  I had to copy-paste the reporter into our
source tree and fix the bug on my end, but now that project is finished and
I've had to move to other things.

For what it's worth, I also had to add 2 more options to disable flowId and
disable captureStandardOutput.  standardOutput capture is not always
desirable; we have tons of output and the capture affects the way it's
rendered.  flowId appeared to be breaking the log rendering, too.  I think
the issue might be that flowId implies parallel test execution, which means
standard output cannot be attributed to any particular test case.  FlowId
is buggy in general, so we handle parallel test execution via running tests
on multiple agents at once.

I hope this feedback is useful.  Thanks for getting back to me.

**Comment by DJ-Glock** [comment]
I had the same question about testFinished message for hooks. I suppose that is should be fixed only when flag recordHookFailures is true, because it does not make any sense to write testFinished message for hook with no testStarted message.

I'll probably will find some time to fix this issue once https://github.com/travisjeffery/mocha-teamcity-reporter/pull/57 is merged.
But I'm talking about problem described in the first message, don't want to touch captureStandardOutput.

**Comment by DJ-Glock** [comment]
@jamie-sherriff if you don't mind, can you hold on with releasing new version for a day or two? I would like to fix this minor issue as well.

**Comment by jamie-sherriff** [comment]
@DJ-Glock  Yup no worries can do both, thanks for picking this up as well.

**Comment by jamie-sherriff** [comment]
@DJ-Glock ill do a release in the next day or so with a major version bump that will include all your changes. Any thoughts on jumping to version 8 to keep in line with mocha versioning?

**Comment by DJ-Glock** [comment]
> @DJ-Glock ill do a release in the next day or so with a major version bump that will include all your changes. Any thoughts on jumping to version 8 to keep in line with mocha versioning?

It’s up to you. I believe that many users can use old versions of mocha for some reason. So you will probably need to add some dependencies on versions of mocha. To restrict users to use old mocha with new reporter.
