### ISSUE TITLE
Issue with running two mocha runs in serial and parallel modes.

### ISSUE THREAD

**Issue by DJ-Glock** [travisjeffery/mocha-teamcity-reporter#55]
## The problem

I use mocha 8.2.1 for running tests and mocha-teamcity-reporter as a reporter for teamcity. I have test files that can be run in parallel. And also I have some test files that should be run one by one - in serial mode. As I understood mocha documentation, mocha can run test files only in parallel or in serial mode. So I tried to do the following: run two mocha runs with & command in one yarn script, like this:

`mocha --reporter mocha-teamcity-reporter --timeout 90000 -r ts-node/register/transpile-only src/Tests/.ts --parallel --jobs 4 & mocha --reporter mocha-teamcity-reporter --timeout 90000 -r ts-node/register/transpile-only src/Tests/seq.ts`

But for some reason using this approach reporter does not work properly. It does not add ##teamcity messages. So TeamCity does not detect all tests that were executed. And this is a big problem :)
I have global hooks that are executed before and after launching each test to log "Started test:" and "Finished test:" messages. So it's was easy to find that some tests are not logged properly:
![image](https://user-images.githubusercontent.com/26511191/109783247-d5080a80-7c1a-11eb-8e11-b16639a19746.png)
![image](https://user-images.githubusercontent.com/26511191/109783377-fbc64100-7c1a-11eb-963a-9764d07cffb2.png)

## Environment

* mocha-teamcity-reporter 3.0.0
* mocha 8.2.1
* yarn 2.3.3
* Version of teamcity does not matter

## Details
I'll be happy to provide any additional information, but not sure what. I believe the issue here is in combined mocha commands. Because when it was only one launch (parallel) everything was fine. My full command for running tests is this:

`"test:smoke_dev": "mocha --reporter mocha-teamcity-reporter --timeout 90000 -r ts-node/register/transpile-only --require src/Generic/mochaHooks.ts src/Tests/**/*prl.e2e.ts src/TestsPoMa/**/*prl.e2e.ts --parallel --jobs 4 --grep '#devsmoke' & mocha --reporter mocha-teamcity-reporter --timeout 90000 -r ts-node/register/transpile-only --require src/Generic/mochaHooks.ts src/Tests/**/*seq.e2e.ts src/TestsPoMa/**/*seq.e2e.ts --grep '#devsmoke'",
`

**Comment by jamie-sherriff** [comment]
Hey @DJ-Glock thanks for the write up and sorry about the delayed response, I have been a bit swamped and hope to give this project some attention in the next week or so.

I had been working on some maintenance items and improved compatibility for mocha 8 in a branch called [feature/maintenance](https://github.com/travisjeffery/mocha-teamcity-reporter/tree/feature/maintenance)
, have you tried giving that a go? 

Something like this should work for installing via npm from a git  branch:

`npm install git://github.com/travisjeffery/mocha-teamcity-reporter.git#feature/maintenance --save`

**Comment by DJ-Glock** [comment]
Hey @jamie-sherriff,
Thanks for your response.
It looks like the latest update of mocha fixed the issue. I need some time to monitor my builds, but I did not see any discrepancy after updating to mocha 8.3.1. Will check several more days and probably will close the issue.

**Comment by DJ-Glock** [comment]
@jamie-sherriff I've created PR to address this issue.
https://github.com/travisjeffery/mocha-teamcity-reporter/pull/57

Can you please check and review? I've added tests to cover this functionality and regression.

**Comment by DJ-Glock** [comment]
I do not see this issue after updating mocha to 8.3.1 so closing. Thanks for your time anyway!
