### ISSUE TITLE
Don't report about root hook start - when recordHookFailures enabled

### ISSUE THREAD

**Issue by DJ-Glock** [travisjeffery/mocha-teamcity-reporter#56]
## The problem
After adding flag recordHookFailures in scope of https://github.com/travisjeffery/mocha-teamcity-reporter/issues/35, the reporter started to add testStarted tag for any hook that was run. So TeamCity is now able to detect hooks as tests, regardless of their state. It works fine for hooks defined in scope of test suite. But it causes another problem - it generates tag for global hooks, including hooks beforeEach and afterEach that are being executed for every test. So when recordHookFailures is enabled we can see much more tests in the TeamCity that we want to see.

## Example
We have a simple test suite with 2 tests, beforeEach, before and after hooks:
```
describe('Login - Login page tests.', () => {
  before('Before hook', async () => {
    console.log('Before hook');
  });

  beforeEach('Before each local hook', async () => {
    console.log('Before each local hook');
  });

  it('Test 1', async () => {
    console.log('Test 1 OK');
  });

  it('Test 2', async () => {
    console.log('Test 2 OK');
  });

  after('After hook', async () => {
    console.log('After hook');
  });
});
```

Also we have a global hooks that run for every test. Example from real life: `beforeEach` logs start of the test (for better navigation in log of parallel tests execution); `afterEach` hook checks test state and creates browser pages screenshot if test failed, if not - it does nothing. Simple example:
```
export const mochaHooks = async () => {
  return {
    beforeEach() {
      console.log(`Before each global hook`);
    },
    afterEach() {
      console.log(`After each global hook`);
    },
  };
};

```

So if we run the following suite with no recordHookFailures parameter, we will get the following log:
`mocha --reporter mocha-teamcity-reporter -r ts-node/register/transpile-only --require src/Generic/mochaHooks.ts src/Tests/**/Test.e2e.ts`

```
##teamcity[testSuiteStarted name='Login - Login page tests.' flowId='22296']
Before hook
##teamcity[testStarted name='Test 1' captureStandardOutput='true' flowId='22296']
Before each global hook
Before each local hook
Test 1 OK
##teamcity[testFinished name='Test 1' duration='0' flowId='22296']
After each global hook
##teamcity[testStarted name='Test 2' captureStandardOutput='true' flowId='22296']
Before each global hook
Before each local hook
Test 2 OK
##teamcity[testFinished name='Test 2' duration='0' flowId='22296']
After each global hook
After hook
##teamcity[testSuiteFinished name='Login - Login page tests.' duration='3' flowId='22296']
```
In TC it will look like this:
![image](https://user-images.githubusercontent.com/26511191/113426069-98772c80-93db-11eb-8ecc-b6cd3e37281c.png)

But if we run the same test suite with recordHookFailures=true parameter, we will get another log:
`mocha --reporter mocha-teamcity-reporter --reporter-options recordHookFailures=true -r ts-node/register/transpile-only --require src/Generic/mochaHooks.ts src/Tests/**/Test.e2e.ts`

```
##teamcity[testSuiteStarted name='Login - Login page tests.' flowId='25512']
##teamcity[testStarted name='"before all" hook: Before hook for "Test 1"' captureStandardOutput='true' flowId='25512']
Before hook
##teamcity[testStarted name='Test 1' captureStandardOutput='true' flowId='25512']
##teamcity[testStarted name='"before each" hook: beforeEach for "Test 1"' captureStandardOutput='true' flowId='25512']
Before each global hook
##teamcity[testStarted name='"before each" hook: Before each local hook for "Test 1"' captureStandardOutput='true' flowId='25512']
Before each local hook
Test 1 OK
##teamcity[testFinished name='Test 1' duration='1' flowId='25512']
##teamcity[testStarted name='"after each" hook: afterEach for "Test 1"' captureStandardOutput='true' flowId='25512']
After each global hook
##teamcity[testStarted name='Test 2' captureStandardOutput='true' flowId='25512']
##teamcity[testStarted name='"before each" hook: beforeEach for "Test 2"' captureStandardOutput='true' flowId='25512']
Before each global hook
##teamcity[testStarted name='"before each" hook: Before each local hook for "Test 2"' captureStandardOutput='true' flowId='25512']
Before each local hook
Test 2 OK
##teamcity[testFinished name='Test 2' duration='1' flowId='25512']
##teamcity[testStarted name='"after each" hook: afterEach for "Test 2"' captureStandardOutput='true' flowId='25512']
After each global hook
##teamcity[testStarted name='"after all" hook: After hook for "Test 2"' captureStandardOutput='true' flowId='25512']
After hook
##teamcity[testSuiteFinished name='Login - Login page tests.' duration='8' flowId='25512']

```
And we will see 8 tests in TeamCity: 2 real tests, 1 before and 1 after hooks, 2 afterEach hooks (global) and 2 beforeEach hooks (I assume global and local hooks were united by TeamCity), so in total there were 10 testStarted messages:
![image](https://user-images.githubusercontent.com/26511191/113426866-bb561080-93dc-11eb-91c7-8ee6dcac2bd2.png)

![image](https://user-images.githubusercontent.com/26511191/113427881-82b73680-93de-11eb-9ab9-56860d2dab79.png)

## Proposed solution
It's great to see all local hooks as tests in TeamCity build.
But we would like to have an ability (another flag) to skip this reporting for global hooks that defined via separate file and parameter in mocha : `--require filename`. Let's say `--ignoreGlobalHooks` flag.

Is it possible?

## Background
Let me give you a context of the problem. I'm trying to implement the ability to mute failed tests and hooks via TeamCity. TeamCity allows to mute tests to make build green. It works fine but only if we disable the following condition: one of build steps exited with an error (e.g non-zero exit code in command line runner):
![image](https://user-images.githubusercontent.com/26511191/113428599-be9ecb80-93df-11eb-88b2-92b4f04a34f6.png)
If we do not disable it, build will be always treated as failed because mocha returns exit code > 0 if any test or hook was failed.
So we decided to switch it off. But we faced another issue - we will not be able to realize that any hook failed because it does not look as a test for TeamCity and exit code is ignored. The only way to see it is to check count of executed test. Not the best way actually. The main issue here is tests that are skipped by mocha because of hook failure. You can check https://github.com/mochajs/mocha/issues/4392 issue for details
So we enabled recordHookFailures flag and faced this issue - a lot of tests appeared in each build.

## Environment
mocha-teamcity-reporter: 3.0.0
mocha: 8.3.2

**Comment by DJ-Glock** [comment]
Hm, I checked your source code and https://github.com/mochajs/mocha/wiki/Third-party-reporters and it looks like it could be not possible. Mocha provides only `hook` and `hook end` events. No word about global hooks :(

**Comment by DJ-Glock** [comment]
I checked your source code and https://github.com/mochajs/mocha/wiki/Third-party-reporters.
Mocha provides only `hook` and `hook end` events. No word about global hooks. But in this case we can try something like this:

1. Add a flag `--skipHooksWithTag="#globalHook"`
2. Implement check:
```
runner.on('hook', function (test) {
	if (recordHookFailures && skipHooksWithTag && title.includes(skipHooksWithTag)) {
		log(formatString(TEST_START, test.title, flowId));
	}
	else if(recordHookFailures){
		log(formatString(TEST_START, test.title, flowId));
	}
});
```

But the only thing I don't understand is how to give a name for [global hook.](https://mochajs.org/#root-hook-plugins) It's not clear for me :(

**Comment by DJ-Glock** [comment]
@jamie-sherriff I've created PR to address this issue.
https://github.com/travisjeffery/mocha-teamcity-reporter/pull/57

Can you please check and review? I've added tests to cover this functionality and regression.

**Comment by jamie-sherriff** [comment]
@DJ-Glock  Thanks very much for this and excellent write up of an issue. I think it might be the best I have ever seen! I will try and review it this week.
