### ISSUE TITLE
Pending tests are displayed as Passed in teamcity UI

### ISSUE THREAD

**Issue by papatelst** [travisjeffery/mocha-teamcity-reporter#65]
## The problem
Briefly describe the issue you are experiencing (or the feature you want to add)
Tests shown as `pending `in Build logs are incorrectly displayed as Passed/Successful in `Overview `and `Tests `tab in teamcity UI.

## Environment

* What mocha-teamcity-reporter version are you using
* 4.1.0
* Version of NPM/yarn etc and Node.js
* npm version 6.14.11, Node.js version 12.21.0
* Version of teamcity (If Applicable)
2020.2.4 (build 86063)
Cypress version - 8.3.0
* Grep library version
* 2.5.3

## Details
* If necessary, describe the problem you have been experiencing in more detail.
* Such as a stacktrace or error message

We use `--env grepTags=@SMOKE` along with following parameters with docker run command
`cypress run --reporter mocha-teamcity-reporter`
Teamcity(TC) buildlog shows tests under Pending and Passing status correctly as shown below
![image](https://user-images.githubusercontent.com/45948323/135539017-91014ba9-300c-4ee0-b046-55e6dcc3d751.png)
However, the TC `overview `tab shows all Pending tests as passed as seen below
![image](https://user-images.githubusercontent.com/45948323/135539096-8caba73a-b7e2-4eac-9315-10a8fef1d250.png)
The TC `Tests `tab shows all tests as successful. When I filter by 'ignored' status, it does not return any tests as shown below.
![image](https://user-images.githubusercontent.com/45948323/135538889-4b6b5e6a-29d2-4b52-a75b-aa1f990829f2.png)
Note: TC does not have test filter statuses like `Pending`, which are mocha specific as mentioned [here](https://github.com/cypress-io/cypress/issues/3092#issuecomment-511611728). The only default filters TC has is `'successful', ''failed' and 'ignored'.`

Differences b/w mocha teamcity reporter and cypress using mocha teamcity reporter can be found [here](https://gist.github.com/fernyb/813ff8764b6dc969f1574df349ae59f9).

Expected behavior:
`Pending `tests from cypress teamcity reporter should display as `Ignored `tests in Teamcity UI. It should not display under 'Successful'/Passed status on TC UI.
## An example test or code sample

* Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
* Not needed for feature requests or questions

**Comment by jamie-sherriff** [comment]
Released in version 4.2.0
